spring:
  kafka:
    stock:
      bootstrap-servers: localhost:7272
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  stock:stock